---

- name: Update repository index
  hosts: all
  become: yes
  pre_tasks:

    - name: Update repository index
      tags: always
      apt:
        update_cache: yes

- name: Add ssh key
  hosts: all
  become: true
  roles:
    - ssh

- name: Deploy nginx microservice in Docker container
  hosts: debian
  become: true
  roles:
    - debian

