- name: Create directory if it doesn't exist
  tags: copy
  file:
    path: "{{ nginx_path }}"
    state: directory

- name: Copy nginx.conf
  tags: copy
  copy:
    src: nginx.conf
    dest: "{{ nginx_config_path }}"
    owner: helhel
    group: helhel
    mode: 0644

- name: Run docker container
  tags: always
  docker_container:
    name: nginx_container
    image: nginx:latest
    state: started
    ports:
      - "8080:80"
    volumes:
      - "{{ nginx_config_path }}:/etc/nginx/nginx.conf"
