- name: Install packages to allow apt to use a repository over HTTPS
  tags: always
  apt:
    name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

- name: Add Docker’s official GPG key
  tags: always
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add the Docker repository
  tags: always
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Install Docker
  tags: always
  apt:
    name: docker-ce
    state: present
